Models/Colaborador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AtividadeCibergestion.Models
{
    public class Colaborador
    {
        [DisplayName("Código")]
        public int ID { get; set; }
        [DisplayName("Nome"), Required]
        public string NomeColaborador { get; set; }
        [DisplayName("Telefone"), Required]
        public string TelefoneColaborador { get; set; }
        [DisplayName("Tipo"), Required]
        public Tipo TipoTelefone { get; set; }
    }

    public enum Tipo
    {
        Celular,
        Residencial,
        Trabalho,
        Whatsapp
    }
}

Controllers/ColaboradorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AtividadeCibergestion.DAO;
using AtividadeCibergestion.Models;

namespace AtividadeCibergestion.Controllers
{
    public class ColaboradorController : Controller
    {
        private ColaboradorContext db = new ColaboradorContext();

        // GET: Colaborador
        public ActionResult Index()
        {
            return View(db.Colaboradores.ToList());
        }

        // GET: Colaborador/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Colaborador colaborador = db.Colaboradores.Find(id);
            if (colaborador == null)
            {
                return HttpNotFound();
            }
            return View(colaborador);
        }

        // GET: Colaborador/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Colaborador/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NomeColaborador,TelefoneColaborador,TipoTelefone")] Colaborador colaborador)
        {
            if (ModelState.IsValid)
            {
                db.Colaboradores.Add(colaborador);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(colaborador);
        }

        // GET: Colaborador/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Colaborador colaborador = db.Colaboradores.Find(id);
            if (colaborador == null)
            {
                return HttpNotFound();
            }
            return View(colaborador);
        }

        // POST: Colaborador/Edit/5
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NomeColaborador,TelefoneColaborador,TipoTelefone")] Colaborador colaborador)
        {
            if (ModelState.IsValid)
            {
                db.Entry(colaborador).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(colaborador);
        }

        // GET: Colaborador/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Colaborador colaborador = db.Colaboradores.Find(id);
            if (colaborador == null)
            {
                return HttpNotFound();
            }
            return View(colaborador);
        }

        // POST: Colaborador/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Colaborador colaborador = db.Colaboradores.Find(id);
            db.Colaboradores.Remove(colaborador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AtividadeCibergestion.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Colaborador/Create.cshtml
@using AtividadeCibergestion.Models
@model AtividadeCibergestion.Models.Colaborador

@{
    ViewBag.Title = "Create";
}

<h2>Criar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Colaborador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomeColaborador, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeColaborador, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeColaborador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefoneColaborador, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefoneColaborador, new { htmlAttributes = new { @class = "form-control", @Type = "tel", @placeholder = "(00) 000000000" } })
                @Html.ValidationMessageFor(model => model.TelefoneColaborador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoTelefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TipoTelefone, new SelectList(Enum.GetValues(typeof(Tipo))), "Selecione o Tipo")
                @Html.ValidationMessageFor(model => model.TipoTelefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

Views/Colaborador/Delete.cshtml
@model AtividadeCibergestion.Models.Colaborador

@{
    ViewBag.Title = "Delete";
}

<h2>Excluir</h2>

<h3>Alerta para exclusão: É irreversível!</h3>
<div>
    <h4>Colaborador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NomeColaborador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeColaborador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelefoneColaborador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelefoneColaborador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoTelefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoTelefone)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" onclick="confirmacao()" /> |
            @Html.ActionLink("Voltar para Lista", "Index")
        </div>
    }
</div>

<script type="text/javascript">

    function confirmacao()
    {
        var resultado = confirm("Deseja realmente excluir?");
        if (resultado)
            return true;
        else
            return false;
    }

</script>

Views/Colaborador/Details.cshtml
@model AtividadeCibergestion.Models.Colaborador

@{
    ViewBag.Title = "Details";
}

    <h2>Detalhes</h2>

<div>
    <h4>Colaborador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NomeColaborador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeColaborador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelefoneColaborador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelefoneColaborador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoTelefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoTelefone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Voltar para Lista", "Index")
</p>

Views/Colaborador/Edit.cshtml
@using AtividadeCibergestion.Models
@model AtividadeCibergestion.Models.Colaborador

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Colaborador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.NomeColaborador, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeColaborador, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeColaborador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefoneColaborador, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefoneColaborador, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefoneColaborador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoTelefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TipoTelefone, new SelectList(Enum.GetValues(typeof(Tipo))), this.Model.TipoTelefone)
                @Html.ValidationMessageFor(model => model.TipoTelefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Colaborador/Index.cshtml
@model IEnumerable<AtividadeCibergestion.Models.Colaborador>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Criar", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Código
        </th>
        <th>
            Nome
        </th>
        <th>
            Telefone
        </th>
        <th>
            Tipo
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.ID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.NomeColaborador)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TelefoneColaborador)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TipoTelefone)
    </td>
    <td>
        @Html.ActionLink("Editar", "Edit", new { id = item.ID }) |
        @Html.ActionLink("Detalhes", "Details", new { id = item.ID }) |
        @Html.ActionLink("Excluir", "Delete", new { id = item.ID })
    </td>
</tr>
}

</table>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Teste Cibergestion</h1>
    <p class="lead">Teste Cibergestion</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Teste Cibergestion</h2>
        <p>
            Teste de CRUD para a empresa Cibergestion
        </p>
    </div>    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Teste Cibergestion</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Teste Cibergestion", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Teste", "Index", "Colaborador")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Teste Cibergestion</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>